### ISSUE TITLE
Q: still necessary?

### ISSUE THREAD

**Issue by marcelstoer** [suculent/esp32-http-update#3]
Is this library in light of https://github.com/espressif/arduino-esp32/commit/febcda0095e9754787eeba3569543c953635da3e still necessary? Does it offer any material benefit over what is in the Arduino core?

**Comment by suculent** [comment]
Hello, Marcel. 

I’ve done this library since this was not working before in Arduino core and I have some projects depending on it. 

Once those will be upgraded, library may be discontinued. 

I just have to find out how :o)

Odesláno z iPhonu

1. 5. 2018 v 22:47, Marcel Stör <notifications@github.com>:

**Comment by suculent** [comment]
See TL;DR in README, this is already deprecated and implemented in Arduino Core.
